#!/usr/bin/env python3
"""
Common constants and station metadata for the data processing package.
"""

from typing import Any, Dict, Tuple

# Central station metadata definition
STATION_METADATA: Dict[str, Dict[str, Any]] = {
    "ZSPD": {
        "station_id": "ZSPD",
        "name": "Shanghai Pudong International Airport",
        "city": "shanghai",
        "country": "cn",
        "latitude": 31.15,
        "longitude": 121.80,
        "elevation": 4.0,
        "timezone": "Asia/Shanghai",
        "temperature_unit": "C",
        "polymarket_id": "shanghai",
        "nws_native": False,
        "iem_network": "CN__ASOS",
        "historical_coverage_pct": 96.2,
        "update_lag_p50_min": 23.2,
        "daily_recs_count": 49,
        "active_polymarket": False,
        "liquidity_usd": 0.0,
        "coastal_microclimate": False,
        "microclimate_score": 85.0,
    },
    "shanghai": {
        "station_id": "ZSPD",
        "name": "Shanghai Pudong International Airport",
        "city": "shanghai",
        "country": "cn",
        "latitude": 31.15,
        "longitude": 121.80,
        "elevation": 4.0,
        "timezone": "Asia/Shanghai",
        "temperature_unit": "C",
        "polymarket_id": "shanghai",
        "nws_native": False,
        "iem_network": "CN__ASOS",
        "historical_coverage_pct": 96.2,
        "update_lag_p50_min": 23.2,
        "active_polymarket": False,
        "liquidity_usd": 0.0,
    },
    "KDEN": {
        "station_id": "KDEN",
        "name": "Denver International Airport",
        "city": "denver",
        "country": "us",
        "latitude": 39.86,
        "longitude": -104.67,
        "elevation": 1655.0,
        "timezone": "America/Denver",
        "temperature_unit": "F",
        "polymarket_id": "denver_legacy_mismatch",
        "audit_status": "SUSPENDED_MISMATCH_AUDIT_001",
        "audit_note": "Polymarket Denver market settles on KBKF (Buckley SFB), not KDEN.",
        "nws_native": True,
        "iem_network": "CO_ASOS",
        "historical_coverage_pct": 99.8,
        "update_lag_p50_min": 20.0,
        "daily_recs_count": 312,
        "active_polymarket": False,
        "liquidity_usd": 0.0,
        "coastal_microclimate": False,
        "microclimate_score": 85.0,
    },

    "KORD": {
        "station_id": "KORD",
        "name": "Chicago O'Hare International Airport",
        "city": "chicago",
        "country": "us",
        "latitude": 41.97,
        "longitude": -87.90,
        "elevation": 205.0,
        "timezone": "America/Chicago",
        "temperature_unit": "F",
        "polymarket_id": "chicago",
        "audit_status": "ADMITTED_TIER_1",
        "nws_native": True,
        "iem_network": "IL_ASOS",
        "historical_coverage_pct": 99.7,
        "update_lag_p50_min": 19.0,
        "daily_recs_count": 311,
        "active_polymarket": True,
        "liquidity_usd": 38000.0,
        "coastal_microclimate": False,
        "microclimate_score": 98.0,
    },
    "KLGA": {
        "station_id": "KLGA",
        "name": "LaGuardia Airport",
        "city": "nyc",
        "country": "us",
        "latitude": 40.77,
        "longitude": -73.87,
        "elevation": 4.0,
        "timezone": "America/New_York",
        "temperature_unit": "F",
        "polymarket_id": "nyc",
        "audit_status": "ADMITTED_TIER_1",
        "nws_native": True,
        "iem_network": "NY_ASOS",
        "historical_coverage_pct": 99.6,
        "update_lag_p50_min": 18.2,
        "daily_recs_count": 313,
        "active_polymarket": True,
        "liquidity_usd": 45000.0,
        "coastal_microclimate": True,
        "microclimate_score": 82.0,
    },
    "KATL": {
        "station_id": "KATL",
        "name": "Hartsfield-Jackson Atlanta International Airport",
        "city": "atlanta",
        "country": "us",
        "latitude": 33.64,
        "longitude": -84.43,
        "elevation": 313.0,
        "timezone": "America/New_York",
        "temperature_unit": "F",
        "polymarket_id": "atlanta",
        "audit_status": "ADMITTED_TIER_1",
        "nws_native": True,
        "iem_network": "GA_ASOS",
        "historical_coverage_pct": 99.7,
        "update_lag_p50_min": 18.0,
        "daily_recs_count": 312,
        "active_polymarket": True,
        "liquidity_usd": 25000.0,
        "coastal_microclimate": False,
        "microclimate_score": 95.0,
    },
    "KDAL": {
        "station_id": "KDAL",
        "name": "Dallas Love Field",
        "city": "dallas",
        "country": "us",
        "latitude": 32.85,
        "longitude": -96.85,
        "elevation": 148.0,
        "timezone": "America/Chicago",
        "temperature_unit": "F",
        "polymarket_id": "dallas",
        "audit_status": "ADMITTED_TIER_1",
        "nws_native": True,
        "iem_network": "TX_ASOS",
        "historical_coverage_pct": 99.1,
        "update_lag_p50_min": 19.8,
        "daily_recs_count": 311,
        "active_polymarket": True,
        "liquidity_usd": 22000.0,
        "coastal_microclimate": False,
        "microclimate_score": 95.0,
    },
    "KSEA": {
        "station_id": "KSEA",
        "name": "Seattle-Tacoma International Airport",
        "city": "seattle",
        "country": "us",
        "latitude": 47.45,
        "longitude": -122.31,
        "elevation": 132.0,
        "timezone": "America/Los_Angeles",
        "temperature_unit": "F",
        "polymarket_id": "seattle",
        "audit_status": "ADMITTED_TIER_2",
        "nws_native": True,
        "iem_network": "WA_ASOS",
        "historical_coverage_pct": 99.4,
        "update_lag_p50_min": 19.0,
        "daily_recs_count": 310,
        "active_polymarket": True,
        "liquidity_usd": 24000.0,
        "coastal_microclimate": True,
        "microclimate_score": 85.0,
    },
    "KLAX": {
        "station_id": "KLAX",
        "name": "Los Angeles International Airport",
        "city": "los angeles",
        "country": "us",
        "latitude": 33.94,
        "longitude": -118.41,
        "elevation": 38.0,
        "timezone": "America/Los_Angeles",
        "temperature_unit": "F",
        "polymarket_id": "los_angeles",
        "audit_status": "ADMITTED_TIER_2",
        "nws_native": True,
        "iem_network": "CA_ASOS",
        "historical_coverage_pct": 99.5,
        "update_lag_p50_min": 18.5,
        "daily_recs_count": 312,
        "active_polymarket": True,
        "liquidity_usd": 26000.0,
        "coastal_microclimate": True,
        "microclimate_score": 80.0,
    },
    "KMIA": {
        "station_id": "KMIA",
        "name": "Miami International Airport",
        "city": "miami",
        "country": "us",
        "latitude": 25.79,
        "longitude": -80.29,
        "elevation": 3.0,
        "timezone": "America/New_York",
        "temperature_unit": "F",
        "polymarket_id": "miami",
        "audit_status": "ADMITTED_TIER_2",
        "nws_native": True,
        "iem_network": "FL_ASOS",
        "historical_coverage_pct": 99.5,
        "update_lag_p50_min": 20.5,
        "daily_recs_count": 317,
        "active_polymarket": True,
        "liquidity_usd": 65000.0,
        "coastal_microclimate": True,
        "microclimate_score": 75.0,
    },
    "KSFO": {
        "station_id": "KSFO",
        "name": "San Francisco International Airport",
        "city": "san francisco",
        "country": "us",
        "latitude": 37.62,
        "longitude": -122.37,
        "elevation": 4.0,
        "timezone": "America/Los_Angeles",
        "temperature_unit": "F",
        "polymarket_id": "san_francisco",
        "audit_status": "ADMITTED_TIER_2",
        "nws_native": True,
        "iem_network": "CA_ASOS",
        "historical_coverage_pct": 99.5,
        "update_lag_p50_min": 18.5,
        "daily_recs_count": 312,
        "active_polymarket": True,
        "liquidity_usd": 18000.0,
        "coastal_microclimate": True,
        "microclimate_score": 75.0,
    },
    "KHOU": {
        "station_id": "KHOU",
        "name": "William P. Hobby Airport",
        "city": "houston",
        "country": "us",
        "latitude": 29.65,
        "longitude": -95.28,
        "elevation": 14.0,
        "timezone": "America/Chicago",
        "temperature_unit": "F",
        "polymarket_id": "houston",
        "audit_status": "ADMITTED_TIER_2",
        "nws_native": True,
        "iem_network": "TX_ASOS",
        "historical_coverage_pct": 99.2,
        "update_lag_p50_min": 19.5,
        "daily_recs_count": 311,
        "active_polymarket": True,
        "liquidity_usd": 12000.0,
        "coastal_microclimate": True,
        "microclimate_score": 80.0,
    },
    "KBKF": {
        "station_id": "KBKF",
        "name": "Buckley Space Force Base Station",
        "city": "denver",
        "country": "us",
        "latitude": 39.70,
        "longitude": -104.75,
        "elevation": 1726.0,
        "timezone": "America/Denver",
        "temperature_unit": "F",
        "polymarket_id": "denver",
        "audit_status": "ADMITTED_TIER_3_WARNING",
        "nws_native": True,
        "iem_network": "CO_ASOS",
        "historical_coverage_pct": 98.4,
        "update_lag_p50_min": 21.5,
        "daily_recs_count": 25,
        "active_polymarket": True,
        "liquidity_usd": 19000.0,
        "coastal_microclimate": False,
        "microclimate_score": 70.0,
    },
    "EGLC": {
        "station_id": "EGLC",
        "name": "London City Airport",
        "city": "london",
        "country": "uk",
        "latitude": 51.51,
        "longitude": 0.05,
        "elevation": 6.0,
        "timezone": "Europe/London",
        "temperature_unit": "C",
        "polymarket_id": "london",
        "audit_status": "REJECTED_NON_NWS",
        "nws_native": False,
        "iem_network": "GB__ASOS",
        "historical_coverage_pct": 97.0,
        "update_lag_p50_min": 25.0,
        "daily_recs_count": 47,
        "active_polymarket": True,
        "liquidity_usd": 25000.0,
        "coastal_microclimate": False,
        "microclimate_score": 85.0,
    },
    "denver": {
        "station_id": "KBKF",
        "name": "Buckley Space Force Base Station",
        "city": "denver",
        "country": "us",
        "latitude": 39.70,
        "longitude": -104.75,
        "elevation": 1726.0,
        "timezone": "America/Denver",
        "temperature_unit": "F",
        "polymarket_id": "denver",
        "audit_status": "ADMITTED_SETTLEMENT_TARGET",
        "nws_native": True,
        "iem_network": "CO_ASOS",
        "historical_coverage_pct": 98.4,
        "update_lag_p50_min": 21.5,
        "active_polymarket": True,
        "liquidity_usd": 15000.0,
    },
    "KAUS": {
        "station_id": "KAUS",
        "name": "Austin-Bergstrom International Airport",
        "city": "austin",
        "country": "us",
        "latitude": 30.19,
        "longitude": -97.67,
        "elevation": 165.0,
        "timezone": "America/Chicago",
        "temperature_unit": "F",
        "polymarket_id": "austin",
        "audit_status": "ADMITTED_TIER_2",
        "nws_native": True,
        "iem_network": "TX_ASOS",
        "historical_coverage_pct": 99.2,
        "update_lag_p50_min": 19.2,
        "daily_recs_count": 312,
        "active_polymarket": True,
        "liquidity_usd": 15000.0,
        "coastal_microclimate": False,
        "microclimate_score": 92.0,
    },
}

# Aliases for backward compatibility and specialized lookups
STATION_COORDINATES: Dict[str, Dict[str, Any]] = {
    k: {
        "latitude": v["latitude"],
        "longitude": v["longitude"],
        "elevation": v["elevation"],
        "name": v["name"],
        "timezone": v["timezone"],
    }
    for k, v in STATION_METADATA.items()
}

STATION_TIMEZONES: Dict[str, str] = {
    k: v["timezone"] for k, v in STATION_METADATA.items()
}

STATION_DEFAULT_UNITS: Dict[str, str] = {
    k: v["temperature_unit"] for k, v in STATION_METADATA.items()
}

# The 11 active US trading stations approved for Phase 1.5/2
ACTIVE_11_STATIONS: Tuple[str, ...] = (
    "KORD",
    "KLGA",
    "KATL",
    "KDAL",
    "KSEA",
    "KLAX",
    "KHOU",
    "KMIA",
    "KSFO",
    "KBKF",
    "KAUS",
)

